apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-chatapp
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: app
  source:
    path: chatapp
    repoURL: https://github.com/TomerDan/chatapp-helm.git
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
